package com.itheima.saas.domain.cargo;

import java.io.Serializable;

public class Finance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.finance_id
     *
     * @mbg.generated
     */
    private String financeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.incoice_id
     *
     * @mbg.generated
     */
    private String incoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.contract_no
     *
     * @mbg.generated
     */
    private String contractNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.export_no
     *
     * @mbg.generated
     */
    private String exportNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.consumer_name
     *
     * @mbg.generated
     */
    private String consumerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.finance_id
     *
     * @return the value of co_finance.finance_id
     *
     * @mbg.generated
     */
    public String getFinanceId() {
        return financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.finance_id
     *
     * @param financeId the value for co_finance.finance_id
     *
     * @mbg.generated
     */
    public void setFinanceId(String financeId) {
        this.financeId = financeId == null ? null : financeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.incoice_id
     *
     * @return the value of co_finance.incoice_id
     *
     * @mbg.generated
     */
    public String getIncoiceId() {
        return incoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.incoice_id
     *
     * @param incoiceId the value for co_finance.incoice_id
     *
     * @mbg.generated
     */
    public void setIncoiceId(String incoiceId) {
        this.incoiceId = incoiceId == null ? null : incoiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.contract_no
     *
     * @return the value of co_finance.contract_no
     *
     * @mbg.generated
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.contract_no
     *
     * @param contractNo the value for co_finance.contract_no
     *
     * @mbg.generated
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.export_no
     *
     * @return the value of co_finance.export_no
     *
     * @mbg.generated
     */
    public String getExportNo() {
        return exportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.export_no
     *
     * @param exportNo the value for co_finance.export_no
     *
     * @mbg.generated
     */
    public void setExportNo(String exportNo) {
        this.exportNo = exportNo == null ? null : exportNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.num
     *
     * @return the value of co_finance.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.num
     *
     * @param num the value for co_finance.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.price
     *
     * @return the value of co_finance.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.price
     *
     * @param price the value for co_finance.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.consumer_name
     *
     * @return the value of co_finance.consumer_name
     *
     * @mbg.generated
     */
    public String getConsumerName() {
        return consumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.consumer_name
     *
     * @param consumerName the value for co_finance.consumer_name
     *
     * @mbg.generated
     */
    public void setConsumerName(String consumerName) {
        this.consumerName = consumerName == null ? null : consumerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.company_id
     *
     * @return the value of co_finance.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.company_id
     *
     * @param companyId the value for co_finance.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.company_name
     *
     * @return the value of co_finance.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.company_name
     *
     * @param companyName the value for co_finance.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}