package com.itheima.saas.domain.cargo;

import java.io.Serializable;
import java.util.Date;

public class Invoice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.invoice_id
     *
     * @mbg.generated
     */
    private String invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.shipping_id
     *
     * @mbg.generated
     */
    private String shippingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.transcompany_name
     *
     * @mbg.generated
     */
    private String transcompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.total_prices
     *
     * @mbg.generated
     */
    private String totalPrices;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.gathering
     *
     * @mbg.generated
     */
    private String gathering;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.state
     *
     * @mbg.generated
     */
    private Long state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.create_dept
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.invoice_id
     *
     * @return the value of co_invoice.invoice_id
     *
     * @mbg.generated
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.invoice_id
     *
     * @param invoiceId the value for co_invoice.invoice_id
     *
     * @mbg.generated
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId == null ? null : invoiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.shipping_id
     *
     * @return the value of co_invoice.shipping_id
     *
     * @mbg.generated
     */
    public String getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.shipping_id
     *
     * @param shippingId the value for co_invoice.shipping_id
     *
     * @mbg.generated
     */
    public void setShippingId(String shippingId) {
        this.shippingId = shippingId == null ? null : shippingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.transcompany_name
     *
     * @return the value of co_invoice.transcompany_name
     *
     * @mbg.generated
     */
    public String getTranscompanyName() {
        return transcompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.transcompany_name
     *
     * @param transcompanyName the value for co_invoice.transcompany_name
     *
     * @mbg.generated
     */
    public void setTranscompanyName(String transcompanyName) {
        this.transcompanyName = transcompanyName == null ? null : transcompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.total_prices
     *
     * @return the value of co_invoice.total_prices
     *
     * @mbg.generated
     */
    public String getTotalPrices() {
        return totalPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.total_prices
     *
     * @param totalPrices the value for co_invoice.total_prices
     *
     * @mbg.generated
     */
    public void setTotalPrices(String totalPrices) {
        this.totalPrices = totalPrices == null ? null : totalPrices.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.gathering
     *
     * @return the value of co_invoice.gathering
     *
     * @mbg.generated
     */
    public String getGathering() {
        return gathering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.gathering
     *
     * @param gathering the value for co_invoice.gathering
     *
     * @mbg.generated
     */
    public void setGathering(String gathering) {
        this.gathering = gathering == null ? null : gathering.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.state
     *
     * @return the value of co_invoice.state
     *
     * @mbg.generated
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.state
     *
     * @param state the value for co_invoice.state
     *
     * @mbg.generated
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.create_by
     *
     * @return the value of co_invoice.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.create_by
     *
     * @param createBy the value for co_invoice.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.create_dept
     *
     * @return the value of co_invoice.create_dept
     *
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.create_dept
     *
     * @param createDept the value for co_invoice.create_dept
     *
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.create_time
     *
     * @return the value of co_invoice.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.create_time
     *
     * @param createTime the value for co_invoice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.company_id
     *
     * @return the value of co_invoice.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.company_id
     *
     * @param companyId the value for co_invoice.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.company_name
     *
     * @return the value of co_invoice.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.company_name
     *
     * @param companyName the value for co_invoice.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}