package com.itheima.saas.domain.cargo;

import java.io.Serializable;
import java.util.Date;

public class Shipping implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.shipping_id
     *
     * @mbg.generated
     */
    private String shippingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.transcompany_id
     *
     * @mbg.generated
     */
    private String transcompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.transcompany_name
     *
     * @mbg.generated
     */
    private String transcompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.packing_ids
     *
     * @mbg.generated
     */
    private String packingIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.state
     *
     * @mbg.generated
     */
    private Long state = 0L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.from_port
     *
     * @mbg.generated
     */
    private String fromPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.to_port
     *
     * @mbg.generated
     */
    private String toPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.receiver_name
     *
     * @mbg.generated
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.receiver_email
     *
     * @mbg.generated
     */
    private String receiverEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.create_dept
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.shipping_id
     *
     * @return the value of co_shipping.shipping_id
     * @mbg.generated
     */
    public String getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.shipping_id
     *
     * @param shippingId the value for co_shipping.shipping_id
     * @mbg.generated
     */
    public void setShippingId(String shippingId) {
        this.shippingId = shippingId == null ? null : shippingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.transcompany_id
     *
     * @return the value of co_shipping.transcompany_id
     * @mbg.generated
     */
    public String getTranscompanyId() {
        return transcompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.transcompany_id
     *
     * @param transcompanyId the value for co_shipping.transcompany_id
     * @mbg.generated
     */
    public void setTranscompanyId(String transcompanyId) {
        this.transcompanyId = transcompanyId == null ? null : transcompanyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.transcompany_name
     *
     * @return the value of co_shipping.transcompany_name
     * @mbg.generated
     */
    public String getTranscompanyName() {
        return transcompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.transcompany_name
     *
     * @param transcompanyName the value for co_shipping.transcompany_name
     * @mbg.generated
     */
    public void setTranscompanyName(String transcompanyName) {
        this.transcompanyName = transcompanyName == null ? null : transcompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.packing_ids
     *
     * @return the value of co_shipping.packing_ids
     * @mbg.generated
     */
    public String getPackingIds() {
        return packingIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.packing_ids
     *
     * @param packingIds the value for co_shipping.packing_ids
     * @mbg.generated
     */
    public void setPackingIds(String packingIds) {
        this.packingIds = packingIds == null ? null : packingIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.state
     *
     * @return the value of co_shipping.state
     * @mbg.generated
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.state
     *
     * @param state the value for co_shipping.state
     * @mbg.generated
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.from_port
     *
     * @return the value of co_shipping.from_port
     * @mbg.generated
     */
    public String getFromPort() {
        return fromPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.from_port
     *
     * @param fromPort the value for co_shipping.from_port
     * @mbg.generated
     */
    public void setFromPort(String fromPort) {
        this.fromPort = fromPort == null ? null : fromPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.to_port
     *
     * @return the value of co_shipping.to_port
     * @mbg.generated
     */
    public String getToPort() {
        return toPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.to_port
     *
     * @param toPort the value for co_shipping.to_port
     * @mbg.generated
     */
    public void setToPort(String toPort) {
        this.toPort = toPort == null ? null : toPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.receiver_name
     *
     * @return the value of co_shipping.receiver_name
     * @mbg.generated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.receiver_name
     *
     * @param receiverName the value for co_shipping.receiver_name
     * @mbg.generated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.receiver_email
     *
     * @return the value of co_shipping.receiver_email
     * @mbg.generated
     */
    public String getReceiverEmail() {
        return receiverEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.receiver_email
     *
     * @param receiverEmail the value for co_shipping.receiver_email
     * @mbg.generated
     */
    public void setReceiverEmail(String receiverEmail) {
        this.receiverEmail = receiverEmail == null ? null : receiverEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.create_by
     *
     * @return the value of co_shipping.create_by
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.create_by
     *
     * @param createBy the value for co_shipping.create_by
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.create_dept
     *
     * @return the value of co_shipping.create_dept
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.create_dept
     *
     * @param createDept the value for co_shipping.create_dept
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.create_time
     *
     * @return the value of co_shipping.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.create_time
     *
     * @param createTime the value for co_shipping.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.company_id
     *
     * @return the value of co_shipping.company_id
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.company_id
     *
     * @param companyId the value for co_shipping.company_id
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.company_name
     *
     * @return the value of co_shipping.company_name
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.company_name
     *
     * @param companyName the value for co_shipping.company_name
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}