package com.itheima.saas.dao.cargo;

import com.itheima.saas.domain.cargo.Contract;
import com.itheima.saas.domain.cargo.ContractExample;
import com.itheima.saas.domain.vo.ContractProductVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ContractDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_contract
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_contract
     *
     * @mbg.generated
     */
    int insert(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_contract
     *
     * @mbg.generated
     */
    int insertSelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_contract
     *
     * @mbg.generated
     */
    List<Contract> selectByExample(ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_contract
     *
     * @mbg.generated
     */
    Contract selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Contract record);

    List<ContractProductVo> findByInputDate(@Param("inputDate") String inputDate,
                                            @Param("companyId") String companyId);
}