package com.itheima.saas.dao.cargo;

import com.itheima.saas.domain.cargo.ExtCproduct;
import com.itheima.saas.domain.cargo.ExtCproductExample;

import java.util.List;

public interface ExtCproductDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    int insert(ExtCproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    int insertSelective(ExtCproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    List<ExtCproduct> selectByExampleWithBLOBs(ExtCproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    List<ExtCproduct> selectByExample(ExtCproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    ExtCproduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExtCproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ExtCproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_cproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExtCproduct record);
}