package com.itheima.saas.domain.baseinfo.systemcode;

import java.io.Serializable;

public class SCProductNo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_productno.productnum_id
     *
     * @mbg.generated
     */
    private String productnumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_productno.productnum
     *
     * @mbg.generated
     */
    private String productnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_productno.factory_id
     *
     * @mbg.generated
     */
    private String factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_productno.factory_name
     *
     * @mbg.generated
     */
    private String factoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_productno.productnum_id
     *
     * @return the value of sc_productno.productnum_id
     *
     * @mbg.generated
     */
    public String getProductnumId() {
        return productnumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_productno.productnum_id
     *
     * @param productnumId the value for sc_productno.productnum_id
     *
     * @mbg.generated
     */
    public void setProductnumId(String productnumId) {
        this.productnumId = productnumId == null ? null : productnumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_productno.productnum
     *
     * @return the value of sc_productno.productnum
     *
     * @mbg.generated
     */
    public String getProductnum() {
        return productnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_productno.productnum
     *
     * @param productnum the value for sc_productno.productnum
     *
     * @mbg.generated
     */
    public void setProductnum(String productnum) {
        this.productnum = productnum == null ? null : productnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_productno.factory_id
     *
     * @return the value of sc_productno.factory_id
     *
     * @mbg.generated
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_productno.factory_id
     *
     * @param factoryId the value for sc_productno.factory_id
     *
     * @mbg.generated
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId == null ? null : factoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_productno.factory_name
     *
     * @return the value of sc_productno.factory_name
     *
     * @mbg.generated
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_productno.factory_name
     *
     * @param factoryName the value for sc_productno.factory_name
     *
     * @mbg.generated
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }
}