package com.itheima.saas.dao.systemlog;

import com.itheima.saas.domain.systemlog.SystemLog;
import com.itheima.saas.domain.systemlog.SystemLogExample;

import java.util.List;
import java.util.Map;

public interface SystemLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sys_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sys_log
     *
     * @mbg.generated
     */
    int insert(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sys_log
     *
     * @mbg.generated
     */
    int insertSelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sys_log
     *
     * @mbg.generated
     */
    List<SystemLog> selectByExample(SystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sys_log
     *
     * @mbg.generated
     */
    SystemLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sys_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sys_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemLog record);

    List<Map<String,String>> selectIpCount();
}